### ISSUE TITLE
Using output dataframe from LCx or LTx for ratio_test

### ISSUE THREAD

**Issue by JennyLuong** [benjaminhlina/ecotox#5]
Hi, is it possible to have an option to pipe that output directly into ratio_test instead of calling the glm model again.

**Comment by benjaminhlina** [comment]
Outputs have been amended from `LC_` and `LT_` functions to have covariance value which is needed for `ratio_test()` to properly calculate differences between values. Previously you had to create two `glm()` objects for each model and put in both objects into the function. `ratio_test()` which will be updated shortly can now handle `glm()` objects or `dataframe` objects that are created by `LC_` and `LT_` functions.
